name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Compress build folder
        run: tar -czf build.tar.gz build/

      - name: Upload tar.gz to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "build.tar.gz"
          target: "/home/ec2-user/"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            FRONT="/usr/share/nginx/html"

            # Limpia el contenido del front
            sudo rm -rf $FRONT/*

            # Directorio temporal
            mkdir -p /home/ec2-user/deploy_tmp

            # Descomprime el build en /deploy_tmp
            tar -xzf /home/ec2-user/build.tar.gz -C /home/ec2-user/deploy_tmp

            # Copia solo el contenido de build/ a /usr/share/nginx/html
            sudo cp -r /home/ec2-user/deploy_tmp/build/* $FRONT

            # Limpieza
            rm -rf /home/ec2-user/deploy_tmp
            rm /home/ec2-user/build.tar.gz

            # Reinicia nginx
            sudo systemctl restart nginx
